name: Deploy on Azure
on:
  push:
    branches: 
    - main

jobs:
  runs-on: ubuntu-latest
  strategy:
      matrix:
        node-version: [20]
  steps:
  - name: Checkout
    uses: actions/checkout@v4
  
  - name: Setup NodeJS ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'

  - name: Caching dependencies
      uses: actions/cache@v3
      id: yarn-cache
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: ${{ runner.os }}-yarn-

  - name: Install packages
      if: steps.yarn-cache.outputs.cache-hit != 'true'
      run: yarn install --frozen-lockfile

  - name: Build
      run: yarn build

  

